controller:
  admissionWebhooks.enabled: false
  replicaCount: 2
  ingressClassResource:
    name: 1c-integration
    enabled: true
    default: true
    controllerValue: "k8s.io/1c-integration-ingress"
  service:
    type: NodePort
    nodePorts:
      http: 30100
    externalTrafficPolicy: Cluster
  scope:
    enabled: true
    namespace: "1c-integration"
  nodeSelector:
    kubernetes.io/os: linux
    node: workload
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true


